apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibliotheque-auth
  namespace: bibliotheque
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bibliotheque-auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bibliotheque-auth
    spec:
      containers:
      - name: auth
        image: touatifadwa/bibliotheque-auth:latest  # Image fixe plutôt que variable
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bibliotheque-secrets
              key: jwt-secret
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-password
        - name: DB_SSL
          value: "true"
        resources:
          limits:
            cpu: "0.5"  # Augmenté pour plus de stabilité
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3002
          initialDelaySeconds: 30  # Délai plus long pour le démarrage
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 5  # Vérification plus fréquente
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3002
          failureThreshold: 30  # 30 tentatives
          periodSeconds: 5  # Toutes les 5 secondes
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: logs-volume
        emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: dockerhub-creds  # À créer si nécessaire pour l'accès privé