apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibliotheque-auth
  namespace: bibliotheque
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bibliotheque-auth
  template:
    metadata:
      labels:
        app: bibliotheque-auth
    spec:
      containers:
      - name: auth
        image: touatifadwa/bibliotheque-microauth:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bibliotheque-secrets
              key: jwt-secret
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bibliotheque-db-secrets
              key: db-password
        - name: DB_SSL
          value: "true"
        - name: PGSSLMODE
          value: "require"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3002
          initialDelaySeconds: 45
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: bibliotheque-auth-service
  namespace: bibliotheque
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30082
  selector:
    app: bibliotheque-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: bibliotheque-secrets
  namespace: bibliotheque
type: Opaque
stringData:
  jwt-secret: "votre_secret_jwt_tres_securise"
---
apiVersion: v1
kind: Secret
metadata:
  name: bibliotheque-db-secrets
  namespace: bibliotheque
type: Opaque
stringData:
  db-host: "ep-delicate-shadow-a4rahkg5-pooler.us-east-1.aws.neon.tech"
  db-port: "5432"
  db-name: "neondb"
  db-user: "neondb_owner"
  db-password: "npg_0wkXyfZg9ild"